# Site settings
title: Riverstone Home Repair
email: brett@riverstonehomerepair.com
description: > # this means to ignore newlines until "baseurl:"
  Riverstone Home Repair. For all your home repair needs. Basied out of
  Sugar Land, Texas.
baseurl: "/stylish-portfolio-jekyll/" # the subpath of your site, e.g. /blog/
url: "http://www.riverstonehomerepair.com" # the base hostname & protocol for your site

# User setting
owner: Brett E. Bond
email: brett@riverstonehomerepair.com
facebook_username:
twitter_username:
github_username:
address: 
  - line: S University Blvd and Kirkpatrick Way
  - line: Missouri City, TX 77479
  # Feel free to add more lines here 
telephone: 832.934.4493
copyright: Riverstone Home Repair

# API settings
google_api_key: AIzaSyBZKJ_G_JcMYUrQ528aaDxHGmrK_E-Ayh8

# Build settings
markdown: kramdown
